[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:nextjs]
command=npm run start
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:evolution]
command=sh -c "npm run db:deploy && npm run start:prod"
directory=/evolution
environment=PORT="8080",API_KEY="apikey_whatscommerce_dev_2026",AUTHENTICATION_API_KEY="apikey_whatscommerce_dev_2026",DATABASE_PROVIDER="postgresql",DATABASE_SAVE_DATA_INSTANCE="true",DATABASE_SAVE_DATA_NEW_MESSAGE="false",DATABASE_SAVE_DATA_CONTACTS="false",DATABASE_SAVE_DATA_CHATS="false",DATABASE_SAVE_DATA_HISTORIC="false"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
